name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-memory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.14.0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: pnpm install --frozen-lockfile
      - run: pnpm check

  build-nats:
    runs-on: ubuntu-latest
    services:
      nats:
        image: nats:2.10
        ports:
          - 4222:4222
        options: >-
          --health-cmd "sh -c 'exec 3<>/dev/tcp/127.0.0.1/4222'"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 20
    env:
      BUS_DRIVER: nats
      NATS_URL: nats://localhost:4222
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.14.0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: pnpm install --frozen-lockfile
      - run: pnpm check
