name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-memory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.14.0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: pnpm install --frozen-lockfile
      - run: pnpm check

  build-nats:
    runs-on: ubuntu-latest
    services:
      nats:
        image: nats:2.10
        ports:
          - 4222:4222
    env:
      BUS_DRIVER: nats
      NATS_URL: nats://localhost:4222
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.14.0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: pnpm install --frozen-lockfile
      - name: Wait for NATS to be ready
        run: |
          echo "Waiting for NATS to be ready..."
          timeout 30s bash -c 'until nc -z localhost 4222; do sleep 1; done'
          echo "NATS is ready!"
      - run: pnpm check
